# VERSION 2 - EDITION 1
# Author: docker_user
# Command format: Instruction [arguments / command] ..

# Base image to use, this must be set as the first line
FROM ubuntu

# Maintainer: docker_user <docker_user at email.com> (@docker_user)
MAINTAINER yahe yahe@email.com

# Commands to update the image
RUN apt-get update && apt-get install -y nginx
RUN apt-get install -y supervisor
RUN echo "\ndaemon off;" >> /etc/nginx/nginx.conf
RUN apt-get install -y php5-fpm openssh-server git
RUN apt-get install -y php5-mysql php5-curl php5-imap php5-ldap php5-memcache php5-gd php5-cli
RUN apt-get install -y memcached
RUN mkdir -p /var/log/supervisor
RUN mkdir -p /var/run/sshd

ADD supervisord.conf /etc/supervisor/conf.d/supervisord.conf
ADD nginx.conf /etc/nginx/nginx.conf
ADD default /etc/nginx/sites-available/default

RUN mkdir -p /usr/share/nginx/www

ADD framework.tar /usr/share/nginx/www

RUN mkdir p /root/.ssh
ADD id_rsa /root/.ssh/id_rsa

ADD main.qa.php /root/main.qa.php
ADD console.qa.php /root/console.qa.php

ADD setup.sh /root/setup.sh

RUN echo "root:123456" | chpasswd

# Commands when creating a new container
EXPOSE 80 22 11211
CMD ["/usr/bin/supervisord"]
