IN-process项目on hold超过30天的

SELECT PRJCT_ID,PRJCT_NAME,PRJCT_DSPLY_NAME,INDSTRY_NAME,SUBINDSTRY_NAME,
BEG_DT,END_DT,PRJCT_STS_UPD_DT,CNSLTN_CLNT_ID AS 'client id',CNSLTN_CLNT_CNTCT_ID AS 'contact id',ON_HOLD_DAY,USER_CRE_DT,CREATOR_NAME
FROM `dw_simp`.`v_prjct`
WHERE `PRJCT_STS_NAME`='in process' AND `ON_HOLD_DAY`>=30;
