DELIMITER $$

USE `dw_simp`$$

DROP PROCEDURE IF EXISTS `create_dw_table`$$

CREATE DEFINER=`root`@`%` PROCEDURE `create_dw_table`()
BEGIN
DROP TABLE IF EXISTS dw_simp.dw_user;
CREATE TABLE dw_simp.dw_user (
	`UID` INT(11) NOT NULL,
  `USER_CHN_NAME` VARCHAR(128) DEFAULT NULL,
  `USER_ENG_NAME` VARCHAR(128) DEFAULT NULL,
  `PSTN_NAME` VARCHAR(128) DEFAULT NULL,
  `DEPT_NAME` VARCHAR(128) DEFAULT NULL,
  `MNGR_IND` TINYINT(4) DEFAULT NULL,
  `TEAM_ID` INT(11) DEFAULT NULL,
  `TEAM_NAME` VARCHAR(128) DEFAULT NULL,
  `EXT_NUM` VARCHAR(255) DEFAULT NULL,
  `EMAIL_ADDR` VARCHAR(128) DEFAULT NULL,
  `USER_ROLE_NAME` VARCHAR(128) DEFAULT NULL,
  `user_sts_cd` INT(11) DEFAULT NULL,
  `SRC_CRE_TS` INT(11) DEFAULT NULL,
  `SRC_CRE_UID` INT(11) DEFAULT NULL,
  `SRC_UPD_TS` INT(11) DEFAULT NULL,
  `SRC_UPD_UID` INT(11) DEFAULT NULL,
  `CRE_TS` INT(11) DEFAULT NULL,
  `CRE_UID` INT(11) DEFAULT NULL,
  `UPD_TS` INT(11) DEFAULT NULL,
  `UPD_UID` INT(11) DEFAULT NULL,	PRIMARY KEY (UID)
)ENGINE=MYISAM DEFAULT CHARSET=utf8;
DROP TABLE IF EXISTS dw_simp.dw_clnt_cntct;
CREATE TABLE dw_simp.dw_clnt_cntct(
	CLNT_CNTCT_ID INT
	,CLNT_ID INT
	,CLNT_CNTCT_NAME VARCHAR(128)
	,PSTN_NAME VARCHAR(128)
	,CNTRY_ID INT,
	PRVNC_STATE_ID INT,
	CITY_ID INT,
	CNTRY_NAME VARCHAR(128),
	PRVNC_STATE_NAME VARCHAR(128),
	CITY_NAME VARCHAR(128)
	,NPS_CD TINYINT
	,ROLE_CD TINYINT
	,MAIN_CNTCT_IND TINYINT
	,CLNT_CNTCT_STS_CD TINYINT
	,CPWEB_RGSTR_STS_CD TINYINT
	,WANT_INVTN_IND TINYINT
	,WANT_INVTN_TYPE_CD TINYINT
	,CLNT_GRP_ID INT
	,USER_CRE_TS INT
	,REM_UID INT
	,SRC_CRE_TS INT
	,SRC_CRE_UID INT
	,SRC_UPD_TS INT
	,SRC_UPD_UID INT
	,CRE_TS INT
	,CRE_UID INT
	,UPD_TS INT
	,UPD_UID INT
	,PRIMARY KEY (CLNT_CNTCT_ID)
	,KEY indx_clientid(CLNT_ID)
) ENGINE=MYISAM DEFAULT CHARSET=utf8;
DROP TABLE IF EXISTS dw_simp.dw_clnt;
CREATE TABLE dw_simp.dw_clnt(
	CLNT_ID INT,
	CLNT_NAME VARCHAR(128),
	CLNT_TYPE_CD INT,
	CLNT_SIZE_BKT_CD INT,
	CNTRY_ID INT,
	PRVNC_STATE_ID INT,
	CITY_ID INT,
	CNTRY_NAME VARCHAR(128),
	PRVNC_STATE_NAME VARCHAR(128),
	CITY_NAME VARCHAR(128),
	CLNT_AM_PCT INT,
	CLNT_AM_UID INT,
	CLNT_AM2_PCT INT,
	CLNT_AM2_UID INT,
	CLNT_AM3_PCT INT,
	CLNT_AM3_UID INT,
	CLNT_AM4_PCT INT,
	CLNT_AM4_UID INT,
	CLNT_STS_CD INT,
	CLNT_STS_NOTE TEXT,
	CLNT_ALERT_NOTE TEXT,
	USER_CRE_UID INT,
	SRC_CRE_TS INT,
	SRC_CRE_UID INT,
	SRC_UPD_TS INT,
	SRC_UPD_UID INT,
	CRE_TS INT,
	CRE_UID INT,
	UPD_TS INT,
	UPD_UID INT,
	CRE_DT DATE,
	CLNT_TEAM VARCHAR(128),
	CLNT_CHRG_TYPE_CD INT,
	PRIMARY KEY (CLNT_ID)
)ENGINE=MYISAM DEFAULT CHARSET=utf8;
DROP TABLE IF EXISTS dw_simp.dw_cnsltnt;
CREATE TABLE dw_simp.dw_cnsltnt (
	CNSLTNT_ID INT NOT NULL,
	CNSLTNT_NAME VARCHAR(128),
	CNSLTNT_STS_CD INT,
	CNTRY_ID INT,
	CNTRY_NAME VARCHAR(128),
	PRVNC_STATE_ID INT,
	PRVNC_STATE_NAME VARCHAR(128),
	CITY_ID INT,
	CITY_NAME VARCHAR(128),
	CNSLTNT_TYPE_CD TINYINT,
	ORGN_CHNL_CD TINYINT,
	ORGN_CHNL_DTL_NAME VARCHAR(128),
	RFRL_CNSLTNT_ID INT,
	RFRL_UID INT,
	PSTN_ID INT,
	PSTN_NAME VARCHAR(128),
	CMPNY_ID INT,
	CMPNY_NAME VARCHAR(500),
	INDSTRY_ID INT,
	INDSTRY_NAME VARCHAR(128),
	SUBINDSTRY_ID INT,
	SUBINDSTRY_NAME VARCHAR(128),
	FNCTN_ID INT,
	FNCTN_NAME VARCHAR(128),
	BCKGRND_CHN_TXT TEXT,
	BCKGRND_ENG_TXT TEXT,
	EXPRTS_CHN_TXT TEXT,
	EXPRTS_ENG_TXT TEXT,
	VALID_EMAIL_IND TINYINT,
	VALID_TEL_IND TINYINT,
	VALID_MBL_IND TINYINT,
	KSH_MBR_IND TINYINT,
	KSH_RGSTR_TS INT,
	FEE_RATE_LC_AMT INT,
	FEE_RATE_CRNCY_CD INT,
	USER_CRE_TS INT,
	USER_CRE_UID INT,
	SRC_CRE_TS INT,
	SRC_CRE_UID INT,
	SRC_UPD_TS INT,
	SRC_UPD_UID INT,
	CRE_TS INT,
	CRE_UID INT,
	UPD_TS INT,
	UPD_UID INT,
	RESUMEBOX_IND INT,
	RESUME_ATTACH_IND INT,
	CRDT_CNT INT,
	CRDT_SPNT INT,
	CRDT_ERN INT,
	LAST_CNTCT_TS INT,
	CNSLTNT_MBL_CNTRY_CODE INT,
	CNSLTNT_TLPHN_CNTRY_CODE INT,
	PRIMARY KEY (CNSLTNT_ID)
) ENGINE=MYISAM DEFAULT CHARSET=utf8;
DROP TABLE IF EXISTS dw_simp.dw_clnt_grp_quota;
CREATE TABLE dw_simp.dw_clnt_grp_quota (
  `month_beg_dt` DATE DEFAULT NULL,
  `clnt_id` INT(11) DEFAULT NULL,
  `clnt_grp_id` INT(11) DEFAULT NULL,
  `quota_hr` DECIMAL(18,2) DEFAULT NULL
) ENGINE=MYISAM DEFAULT CHARSET=utf8;
DROP TABLE IF EXISTS dw_simp.dw_clnt_quota;
CREATE TABLE dw_simp.dw_clnt_quota(
month_beg_dt DATE,
clnt_id INT,
quota_hr DECIMAL(18,2)
)ENGINE=MYISAM DEFAULT CHARSET=utf8;
DROP TABLE IF EXISTS dw_simp.dw_prjct;
CREATE TABLE dw_simp.dw_prjct(
	PRJCT_ID INT NOT NULL,
	PRJCT_NAME VARCHAR(500),
	PRJCT_DSPLY_NAME VARCHAR(500),
	PRJCT_DESC TEXT,
	PRJCT_CLNT_CASE_CD VARCHAR(64),
	PRJCT_CTGRY_CD TINYINT,
	PRJCT_STS_CD TINYINT,
	PRJCT_STS_UPD_TS INT,
	PRJCT_KEYQSTN_TXT TEXT,
	INDSTRY_ID INT,
	INDSTRY_NAME VARCHAR(500),
	SUBINDSTRY_ID INT,
	SUBINDSTRY_NAME VARCHAR(128),
	BEG_TS INT,
	END_TS INT,
	RQST_CNSLTNT_CNT INT,
	EXPCT_CNSLTNT_CNT INT,
	RCMND_TASK_CNT INT,
	ARNG_TASK_CNT INT,
	CMPLT_TASK_CNT INT,
	
	RCMND_CNSLTNT_CNT INT,
	ARNG_CNSLTNT_CNT INT,
	CMPLT_CNSLTNT_CNT INT,
	CNSLTNT_HR DECIMAL(8,2),
	PRJCT_QLTY_CD TINYINT,
	PRJCT_WLNG_IND TINYINT,
	PRJCT_NOTE TEXT,
	
	CNSLTN_CLNT_ID INT,
	CNSLTN_CLNT_CNTCT_ID INT,
	CNSLTN_CLNT_CNTCT_MNGR_ID INT,
	AM_UID INT,
	PRJCT_MNGR_UID INT,
	SKM_UID INT,
	ON_HOLD_DAY INT,
	USER_CRE_TS INT,
	USER_CRE_UID INT,
	SRC_CRE_TS INT,
	SRC_CRE_UID INT,
	SRC_UPD_TS INT,
	SRC_UPD_UID INT,
	CRE_TS INT,
	CRE_UID INT,
	UPD_TS INT,
	UPD_UID INT,
	PRIMARY KEY (PRJCT_ID),
	KEY idx_userid(CRE_UID),
	KEY idx_clientid(CNSLTN_CLNT_ID),
	KEY idx_contactid(CNSLTN_CLNT_CNTCT_ID),
	KEY idx_managercontactid(CNSLTN_CLNT_CNTCT_MNGR_ID),
	KEY idx_manageruserid(PRJCT_MNGR_UID)
)  ENGINE=MYISAM DEFAULT CHARSET=utf8;
DROP TABLE IF EXISTS dw_simp.dw_prjct_task;
CREATE TABLE dw_simp.dw_prjct_task(
    TASK_ID INT NOT NULL,
	PRJCT_ID INT,
	TASK_STS_CD TINYINT,
	TASK_STS_UPD_TS INT,
	TASK_TYPE_CD TINYINT,
	task_rgn_cd TINYINT,
	BEG_TS INT,
	END_TS INT,
	TASK_MNGR_ID INT,
	CLNT_ID INT,
	CLNT_CNTCT_ID INT,
	CNSLTNT_ID INT,
	PAY_STS_CD INT,
	CNSLTNT_PAY_IND TINYINT,
	CNSLTNT_CNY_AMT DECIMAL(18,2),
	CNSLTNT_HR DECIMAL(18,2),
	CNSLTNT_PAY_TS INT,
	CNSLTNT_PAY_TYPE_CD TINYINT,
	CNSLTNT_PAY_CRNCY_CD INT,
	CNSLTNT_PAY_NOTE TEXT,
	CLNT_CNY_AMT DECIMAL(18,2),
	CLNT_HR DECIMAL(18,2),
	CLNT_PAY_TS INT,
	CNSLTN_TYPE_CD TINYINT,
	CNSLTNT_FDBK_CMNCTN_SCORE TINYINT,
	CNSLTNT_FDBK_EXPRTS_SCORE TINYINT,
	CNSLTNT_FDBK_PRFSNLSM_SCORE TINYINT,
	CNSLTNT_FDBK_NOTE TEXT,
	CNSLTNT_FIRST_CALL_IND TINYINT,
	CNSLTNT_PSTN_ID INT,
	CNSLTNT_PSTN_NAME VARCHAR(128),
	CNSLTNT_CMPNY_ID INT,
	CNSLTNT_CMPNY_NAME VARCHAR(500),
	CNSLTNT_INDSTRY_ID INT,
	CNSLTNT_INDSTRY_NAME VARCHAR(128),
	CNSLTNT_SUBINDSTRY_ID INT,
	CNSLTNT_SUBINDSTRY_NAME VARCHAR(128),
	TASK_INDSTRY_ID INT,
	TASK_INDSTRY_NAME VARCHAR(128),
	CMPLT_TS INT,
	USER_CRE_TS INT,
	USER_CRE_UID INT,
	SRC_CRE_TS INT,
	SRC_CRE_UID INT,
	SRC_UPD_TS INT,
	SRC_UPD_UID INT,
	CRE_TS INT,
	CRE_UID INT,
	UPD_TS INT,
	UPD_UID INT,
	RCMND_IND INT,
	FIRST_RCMND_DT DATE,
	LAST_RCMND_DT DATE,
	ARNG_IND INT,
	FIRST_ARNG_DT DATE,
	LAST_ARNG_DT DATE,
	RCMND_CNTCT_IND INT,
	CMPLT_IND  INT,
	PRIMARY KEY (TASK_ID),
	KEY PRJCT_ID (PRJCT_ID),
	KEY TASK_CNTCT_ID (CLNT_CNTCT_ID),
	KEY TASK_INDSTRY_ID (TASK_INDSTRY_ID),
	KEY TASK_CLIENT_ID (CLNT_ID),
	KEY TASK_CNSLTNT_ID (CNSLTNT_ID)
)ENGINE=MYISAM DEFAULT CHARSET=utf8;
DROP TABLE IF EXISTS dw_simp.dw_cnsltnt_err;
DROP TABLE IF EXISTS dw_simp.dw_clnt_err;
DROP TABLE IF EXISTS dw_simp.dw_clnt_cntct_err;
DROP TABLE IF EXISTS dw_simp.dw_prjct_err;
DROP TABLE IF EXISTS dw_simp.dw_prjct_task_err;
CREATE TABLE dw_simp.dw_cnsltnt_err LIKE dw_simp.dw_cnsltnt;
CREATE TABLE dw_simp.dw_clnt_err LIKE dw_simp.dw_clnt;
CREATE TABLE dw_simp.dw_clnt_cntct_err LIKE dw_simp.dw_clnt_cntct;
CREATE TABLE dw_simp.dw_prjct_err LIKE dw_simp.dw_prjct;
CREATE TABLE dw_simp.dw_prjct_task_err LIKE dw_simp.dw_prjct_task;
DROP TABLE IF EXISTS  dw_simp.`vesta_consultant`;
CREATE TABLE dw_simp.`vesta_consultant` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) DEFAULT NULL COMMENT '姓名',
  `gender` TINYINT(1) DEFAULT NULL COMMENT '性别',
  `residence` VARCHAR(500) DEFAULT NULL COMMENT '居住地',
  `expertise` VARCHAR(500) DEFAULT NULL COMMENT '个人专长',
  `background` TEXT COMMENT '个人简介',
  `subscribe_mail` TINYINT(1) DEFAULT NULL COMMENT '订阅邮件',
  `ndb_id` INT(11) UNSIGNED DEFAULT '0' COMMENT 'NDB对应ID',
  `sign_tnc` INT(10) UNSIGNED DEFAULT NULL COMMENT '签约T&C时间',
  `referral_vesta_id` INT(11) UNSIGNED DEFAULT NULL COMMENT '邀请者',
  `source` TINYINT(3) UNSIGNED DEFAULT NULL COMMENT '来源',
  `birthday` VARCHAR(10) DEFAULT NULL COMMENT '生日',
  `source_desc` VARCHAR(500) DEFAULT NULL COMMENT '来源描述',
  `firstname` VARCHAR(64) DEFAULT NULL COMMENT '名',
  `lastname` VARCHAR(64) DEFAULT NULL COMMENT '姓',
  `nickname` VARCHAR(64) DEFAULT NULL COMMENT '昵称',
  `mobile` VARCHAR(128) DEFAULT NULL COMMENT '手机号码',
  `wechat` VARCHAR(128) DEFAULT NULL COMMENT '微信号',
  `tncid` INT(10) UNSIGNED DEFAULT NULL COMMENT 'tncid',
  `auth_status` TINYINT(2) DEFAULT '0' COMMENT '1 认证通过 0 未认证或者没有通过',
  `ndb_status` VARCHAR(45) DEFAULT NULL COMMENT '状态',
  `completed_consultation_count` INT(11) DEFAULT NULL COMMENT '完成访谈数量',
  `is_senior` TINYINT(1) DEFAULT '0' COMMENT '是否高级顾问',
  `email_checked` TINYINT(2) DEFAULT '1' COMMENT '邮箱是否验证  1验证  0未验证',
  PRIMARY KEY (`id`),
  UNIQUE KEY `nickname` (`nickname`)
) ENGINE=INNODB AUTO_INCREMENT=21385 DEFAULT CHARSET=utf8;
DROP TABLE IF EXISTS dw_simp.`vesta_user`;
CREATE TABLE dw_simp.`vesta_user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) DEFAULT NULL COMMENT 'EMAIL',
  `user` VARCHAR(255) DEFAULT NULL COMMENT '用户登入名',
  `password` VARCHAR(100) DEFAULT NULL COMMENT '密码',
  `create_time` INT(10) DEFAULT NULL COMMENT '注册时间',
  `last_login_time` INT(10) DEFAULT NULL COMMENT '上次登入时间',
  `last_login_ip` VARCHAR(100) DEFAULT NULL COMMENT '上次登入IP',
  `account_type` TINYINT(3) UNSIGNED DEFAULT '1' COMMENT '账户类型 1 - 内部  2 - 外部',
  `account_status` TINYINT(3) UNSIGNED DEFAULT '1' COMMENT '账户状态  0 - 停用  1 - 启用',
  `update_time` INT(10) DEFAULT NULL COMMENT '更新时间',
  `expired_time` INT(10) DEFAULT NULL COMMENT '过期时间',
  `login_count` INT(10) UNSIGNED DEFAULT '0' COMMENT '登入次数',
  `ndb_id` INT(11) UNSIGNED DEFAULT NULL COMMENT 'NDB顾问ID',
  `apptoken` VARCHAR(255) DEFAULT NULL COMMENT '手机APPTOKEN',
  `mobile` VARCHAR(20) DEFAULT '' COMMENT '手机号码',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx1_vesta_user` (`user`),
  KEY `idx2_vesta_user` (`email`),
  KEY `idx3_vesta_user` (`mobile`)
) ENGINE=INNODB AUTO_INCREMENT=21385 DEFAULT CHARSET=utf8;
END$$

DELIMITER ;