DELIMITER $$

USE `dw_simp`$$

DROP FUNCTION IF EXISTS `IsNum`$$

CREATE DEFINER=`root`@`%` FUNCTION `IsNum`(str VARCHAR(500)) RETURNS INT(11)
BEGIN
DECLARE iResult INT DEFAULT 0;
IF ISNULL(str) THEN RETURN 0; END IF;
IF str = '' THEN RETURN 0; END IF;
SELECT str REGEXP '^[0-9]*$' INTO iResult;
IF iResult = 1 THEN
RETURN 1;
ELSE
RETURN 0;
END IF;
END$$

DELIMITER ;