/*
spring - 最近1月凯盛汇注册了多少用户
*/


SELECT DATE(FROM_UNIXTIME(create_time)),COUNT(*) FROM vesta_user 
WHERE create_time BETWEEN UNIX_TIMESTAMP('2015-10-31') AND UNIX_TIMESTAMP('2015-11-30')
GROUP BY DATE(FROM_UNIXTIME(create_time))
ORDER BY DATE(FROM_UNIXTIME(create_time)) ASC


SELECT DATE(FROM_UNIXTIME(lastlogintime)),COUNT(*) FROM capweb_user 
WHERE lastlogintime BETWEEN UNIX_TIMESTAMP('2015-10-31') AND UNIX_TIMESTAMP('2015-11-30')
GROUP BY DATE(FROM_UNIXTIME(lastlogintime))
ORDER BY DATE(FROM_UNIXTIME(lastlogintime)) ASC